version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./cpp/Dockerfile
    command: server
    ports:
      - 50051:50051
  client:
    build:
      context: .
      dockerfile: ./cpp/Dockerfile
    command: client
    depends_on:
      - server
